version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - minio
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  minio_data:
  pgdata: 